# Define the network structure

edges = [
	('Quadratmeter', 'Zimmerzahl'),
	('Quadratmeter', 'Miete'),
	('Garage', 'Miete'),
	('Stockwerk', 'Aufzug'),
	('Stockwerk', 'Terrasse'),
	('Alter', 'Kueche'),
	('Alter', 'Stockwerk'),
	('Balkon', 'Terrasse'),
	('Lage', 'S-Bahn'),
	('Lage', 'Entfernung'),
	('Lage', 'Kindergarten'),
	('Lage', 'Schule'),
	('Miete', 'Kaution'),
	('Kueche', 'Kaution'),
	('Hausmeister', 'Nebenkosten'),
	('Hausmeister', 'Kehrwoche'),
	('Nebenkosten', 'Kleinfamilie'),
	('Zimmerzahl', 'Kleinfamilie'),
	('Kaution', 'Kleinfamilie'),
	('Miete', 'Kleinfamilie'),
	('Bad', 'Kleinfamilie'),
	('Kueche', 'Kleinfamilie'),
	('Kindergarten', 'Kleinfamilie'),
	('Schule', 'Kleinfamilie'),
	('Miete', 'Studierende'),
	('Kaution', 'Studierende'),
	('Nebenkosten', 'Studierende'),
	('Entfernung', 'Studierende'),
	('S-Bahn', 'Studierende'),
	('Kueche', 'Expatriate'),
	('Bad', 'Expatriate'),
	('S-Bahn', 'Expatriate'),
	('Entfernung', 'Expatriate'),
	('Kehrwoche', 'Expatriate'),
	('Hausmeister', 'Expatriate'),
	('Miete', 'Rentnerpaar'),
	('Kueche', 'Rentnerpaar'),
	('Stockwerk', 'Rentnerpaar'),
	('Aufzug', 'Rentnerpaar'),
	('Garage', 'Rentnerpaar'),
	('Balkon', 'Rentnerpaar'),
	('Terrasse', 'Rentnerpaar'),
	('Bad', 'Rentnerpaar'),
	('Bad', 'DINK'),
	('Kueche', 'DINK'),
	('Balkon', 'DINK'),
	('Terrasse', 'DINK'),
	('S-Bahn', 'DINK'),
	('Garage', 'DINK'),
	('Entfernung', 'DINK'),
	('S-Bahn', 'SingleHighIncome'),
	('Entfernung', 'SingleHighIncome'),
	('Garage', 'SingleHighIncome'),
	('Balkon', 'SingleHighIncome'),
	('Terrasse', 'SingleHighIncome'),
	('Bad', 'SingleHighIncome'),
	('Kueche', 'SingleHighIncome')
]

nodes = ['Kleinfamilie', 'Studierende', 'Expatriate', 'Rentnerpaar', 'DINK', 'SingleHighIncome', "Zimmerzahl","Stockwerk","Hausmeister","Kindergarten","Schule","S-Bahn","Garage","Miete","Nebenkosten","Alter","Aufzug","Lage","Entfernung","Kaution","Kueche","Bad","Balkon","Terrasse","Kehrwoche","Quadratmeter"]
